---
title: "Bea_rm)moths"
author: "Ben Wilson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bea's Code - Moths

```{Bea's moth code, echo=TRUE}

library(tidyverse)
library(ggplot2)
library(viridisLite)
library(viridis)
library(hrbrthemes)
library(wesanderson)
library(dplyr)

moths <-wesandersonmoths <- read.csv("Chi1.csv")
glimpse(moths)

moth_table <- table(moths$Species, moths$Site)
moth_table 

chisq.test(moth_table, simulate.p.value = TRUE)

chisq.test(moth_table, correct = TRUE)

plot(moth_table)

ggplot(moths, aes(fill=Site, y=Count, x=Species)) + 
  geom_bar(position="dodge", stat="identity")

ggplot(moths, aes(fill=Site, y=Count, x=Species)) + 
  geom_bar(position="stack", stat="identity")

ggplot(moths, aes(fill=Site, y=Count, x=Species)) + 
  geom_bar(position="stack", stat="identity")+
  scale_fill_manual(values = wes_palette("GrandBudapest2")) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1)) +
  coord_cartesian(ylim = c(0,50))
